const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Tween,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerLoad,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.JavaScriptInEvents.Gameplay_Event19_Act2,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.System.Acts.AddVar,
		C3.JavaScriptInEvents.Gameplay_Event20_Act2,
		C3.JavaScriptInEvents.Gameplay_Event21_Act2,
		C3.JavaScriptInEvents.Gameplay_Event22_Act2,
		C3.JavaScriptInEvents.Gameplay_Event23_Act2,
		C3.JavaScriptInEvents.Gameplay_Event24_Act2,
		C3.JavaScriptInEvents.Gameplay_Event25_Act2,
		C3.JavaScriptInEvents.Gameplay_Event26_Act2,
		C3.JavaScriptInEvents.Gameplay_Event27_Act2,
		C3.JavaScriptInEvents.Gameplay_Event28_Act2,
		C3.JavaScriptInEvents.Gameplay_Event30_Act4,
		C3.Plugins.PlatformInfo.Cnds.IsOnWindows,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.PlatformInfo.Cnds.IsOnMobile,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.JavaScriptInEvents.Gameplay_Event45_Act2,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.Plugins.Eponesh_GameScore.Acts.LeaderboardOpen,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Gameplay_Event51_Act3,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedAvailable,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.JavaScriptInEvents.Gameplay_Event55_Act4,
		C3.JavaScriptInEvents.Gameplay_Event55_Act9,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.Plugins.Eponesh_GameScore.Cnds.Language,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.JavaScriptInEvents.Gameplay_Event70_Act1,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.JavaScriptInEvents.Gameplay_Event77_Act2,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenAvailable,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.JavaScriptInEvents.Gameplay_Event82_Act1,
		C3.JavaScriptInEvents.Gameplay_Event83_Act2,
		C3.JavaScriptInEvents.Gameplay_Event83_Act3,
		C3.JavaScriptInEvents.Gameplay_Event83_Act4,
		C3.JavaScriptInEvents.Gameplay_Event83_Act5,
		C3.JavaScriptInEvents.Gameplay_Event83_Act6,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.JavaScriptInEvents.Gameplay_Event84_Act1
	];
};
self.C3_JsPropNameTable = [
	{destroyed: 0},
	{Физика: 0},
	{Твинанимация: 0},
	{ObjectMach: 0},
	{bombe: 0},
	{background: 0},
	{Твердый: 0},
	{gamezone: 0},
	{granitsa: 0},
	{linezone: 0},
	{restart: 0},
	{settings: 0},
	{score: 0},
	{bestscore: 0},
	{scoretext: 0},
	{TT: 0},
	{TT2: 0},
	{touch: 0},
	{Browser: 0},
	{recordtext: 0},
	{audio: 0},
	{naklad: 0},
	{mouse: 0},
	{ustroistvo: 0},
	{Синусоид: 0},
	{bomba: 0},
	{GameScore: 0},
	{boomo: 0},
	{localstorage: 0},
	{record: 0},
	{klava: 0},
	{invite: 0},
	{public: 0},
	{volume: 0},
	{losetable: 0},
	{restartbtn: 0},
	{scoretxt: 0},
	{nwrcrdtxt: 0},
	{scorelose: 0},
	{zatemnenie: 0},
	{adstet: 0},
	{Спрайт: 0},
	{ObjectMachs: 0},
	{create: 0},
	{timer: 0},
	{bomb: 0},
	{createbom: 0},
	{vlume: 0},
	{adss: 0},
	{tads: 0},
	{adMuteHold: 0},
	{CurrentPlatform: 0},
	{frame: 0}
];

self.InstanceType = {
	ObjectMach: class extends self.ISpriteInstance {},
	bombe: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	gamezone: class extends self.ISpriteInstance {},
	granitsa: class extends self.ISpriteInstance {},
	linezone: class extends self.ISpriteInstance {},
	restart: class extends self.ISpriteInstance {},
	settings: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	bestscore: class extends self.ISpriteInstance {},
	scoretext: class extends self.ITextInstance {},
	TT: class extends self.ITextInstance {},
	TT2: class extends self.ITextInstance {},
	touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	recordtext: class extends self.ITextInstance {},
	audio: class extends self.IInstance {},
	naklad: class extends self.ISpriteInstance {},
	mouse: class extends self.IInstance {},
	ustroistvo: class extends self.IInstance {},
	bomba: class extends self.ISpriteInstance {},
	GameScore: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	boomo: class extends self.ISpriteInstance {},
	localstorage: class extends self.IInstance {},
	record: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	invite: class extends self.ISpriteInstance {},
	public: class extends self.ISpriteInstance {},
	volume: class extends self.ISpriteInstance {},
	losetable: class extends self.ISpriteInstance {},
	restartbtn: class extends self.ISpriteInstance {},
	scoretxt: class extends self.ISpriteInstance {},
	nwrcrdtxt: class extends self.ISpriteInstance {},
	scorelose: class extends self.ITextInstance {},
	zatemnenie: class extends self.ISpriteInstance {},
	adstet: class extends self.ITextInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	ObjectMachs: class extends self.ISpriteInstance {}
}