const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.Platform,
		C3.Plugins.Particles,
		C3.Plugins.Browser,
		C3.Plugins.Eponesh_GameScore,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Eponesh_GameScore.Exps.PlayerGet,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Eponesh_GameScore.Acts.AnalyticsGoal,
		C3.JavaScriptInEvents.Game_Event1_Act3,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowSticky,
		C3.Plugins.System.Cnds.EveryTick,
		C3.JavaScriptInEvents.Game_Event2_Act1,
		C3.JavaScriptInEvents.Game_Event3_Act1,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.JavaScriptInEvents.Game_Event8,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSet,
		C3.Plugins.Eponesh_GameScore.Acts.PlayerSync,
		C3.JavaScriptInEvents.Game_Event12_Act3,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsPreloaderPlaying,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsFullscreenPlaying,
		C3.JavaScriptInEvents.Game_Event14_Act1,
		C3.JavaScriptInEvents.Game_Event15_Act1,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowFullscreen,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsFullscreenClose,
		C3.JavaScriptInEvents.Game_Event17_Act1,
		C3.JavaScriptInEvents.Game_Event18_Act1,
		C3.JavaScriptInEvents.Game_Event19_Act1,
		C3.JavaScriptInEvents.Game_Event19_Act2,
		C3.JavaScriptInEvents.Game_Event20_Act1,
		C3.Plugins.Eponesh_GameScore.Cnds.IsAdsRewardedPlaying,
		C3.JavaScriptInEvents.Game_Event21_Act1,
		C3.JavaScriptInEvents.Game_Event22_Act1,
		C3.JavaScriptInEvents.Game_Event22_Act2,
		C3.JavaScriptInEvents.Game_Event24_Act1,
		C3.JavaScriptInEvents.Game_Event24_Act2,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedClose,
		C3.JavaScriptInEvents.Game_Event25_Act1,
		C3.JavaScriptInEvents.Game_Event25_Act2,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsPreloaderClose,
		C3.JavaScriptInEvents.Game_Event26_Act1,
		C3.JavaScriptInEvents.Game_Event26_Act2,
		C3.Plugins.Eponesh_GameScore.Cnds.OnAdsRewardedReward,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Eponesh_GameScore.Acts.AdsShowRewarded,
		C3.JavaScriptInEvents.Game_Event29_Act1,
		C3.JavaScriptInEvents.Game_Event29_Act2,
		C3.Plugins.System.Cnds.OnSuspend,
		C3.JavaScriptInEvents.Game_Event30_Act1,
		C3.JavaScriptInEvents.Game_Event30_Act2,
		C3.Plugins.System.Cnds.OnResume,
		C3.JavaScriptInEvents.Game_Event31_Act1,
		C3.JavaScriptInEvents.Game_Event31_Act2,
		C3.Plugins.Eponesh_GameScore.Acts.GameStart,
		C3.Plugins.Eponesh_GameScore.Acts.SocialsInvite,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Твердый: 0},
	{PlatformsTilemap: 0},
	{Player: 0},
	{klava: 0},
	{touch: 0},
	{back1: 0},
	{back2: 0},
	{fon: 0},
	{BackgroundTilemap: 0},
	{Audio: 0},
	{gamefon: 0},
	{DeathZone: 0},
	{Угасание: 0},
	{backlvl: 0},
	{Синусоида: 0},
	{solid: 0},
	{MovingStone: 0},
	{stonetd: 0},
	{Solid: 0},
	{Sand: 0},
	{FlashState: 0},
	{Dynamite: 0},
	{Пуля: 0},
	{Заворачивание: 0},
	{cloud: 0},
	{Platform: 0},
	{PlayerBox: 0},
	{Ice: 0},
	{Slime: 0},
	{Cactus: 0},
	{DirX: 0},
	{Dispenser: 0},
	{Arrow: 0},
	{portalfon: 0},
	{Portal: 0},
	{Fireflies: 0},
	{DarkScreen: 0},
	{LightGlow: 0},
	{fakel: 0},
	{browser: 0},
	{GamePush: 0},
	{Lava: 0},
	{LavaFon: 0},
	{MirrorDir: 0},
	{PlaySound: 0},
	{MaxLevel: 0},
	{TriggerSave: 0},
	{IsRewardEarned: 0},
	{URL: 0}
];

self.InstanceType = {
	PlatformsTilemap: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	klava: class extends self.IInstance {},
	touch: class extends self.IInstance {},
	back1: class extends self.ITilemapInstance {},
	back2: class extends self.ITilemapInstance {},
	fon: class extends self.ISpriteInstance {},
	BackgroundTilemap: class extends self.ITilemapInstance {},
	Audio: class extends self.IInstance {},
	gamefon: class extends self.ITilemapInstance {},
	DeathZone: class extends self.ISpriteInstance {},
	backlvl: class extends self.ISpriteInstance {},
	MovingStone: class extends self.ISpriteInstance {},
	stonetd: class extends self.ISpriteInstance {},
	Sand: class extends self.ISpriteInstance {},
	Dynamite: class extends self.ISpriteInstance {},
	cloud: class extends self.ISpriteInstance {},
	PlayerBox: class extends self.ISpriteInstance {},
	Ice: class extends self.ISpriteInstance {},
	Slime: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	Dispenser: class extends self.ISpriteInstance {},
	Arrow: class extends self.ISpriteInstance {},
	portalfon: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	Fireflies: class extends self.IParticlesInstance {},
	DarkScreen: class extends self.ISpriteInstance {},
	LightGlow: class extends self.ISpriteInstance {},
	fakel: class extends self.ISpriteInstance {},
	browser: class extends self.IInstance {},
	GamePush: class extends C3.Plugins.Eponesh_GameScore.Instance {},
	Lava: class extends self.ISpriteInstance {},
	LavaFon: class extends self.ISpriteInstance {}
}