const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.scrollto,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.PlaygamaBridge,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.JavaScriptInEvents.Egame_Event1_Act2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerParallax,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.PlaygamaBridge.Acts.SetMinimumDelayBetweenInterstitial,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.Wait,
		C3.JavaScriptInEvents.Egame_Event5_Act2,
		C3.JavaScriptInEvents.Egame_Event5_Act5,
		C3.Plugins.PlaygamaBridge.Cnds.IsInterstitialSupported,
		C3.Plugins.PlaygamaBridge.Acts.ShowInterstitial,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.JavaScriptInEvents.Egame_Event17_Act1,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.JavaScriptInEvents.Emenu_Event3_Act1,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Emenu_Event4_Act2,
		C3.JavaScriptInEvents.Emenu_Event5_Act2,
		C3.JavaScriptInEvents.Emenu_Event6_Act2,
		C3.JavaScriptInEvents.Emenu_Event18_Act1,
		C3.JavaScriptInEvents.Emenu_Event20_Act3,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.JavaScriptInEvents.Emenu_Event26_Act1,
		C3.Plugins.LocalStorage.Cnds.CompareValue
	];
};
self.C3_JsPropNameTable = [
	{EasyBtn: 0},
	{MediumBtn: 0},
	{HardBtn: 0},
	{GameModeBack: 0},
	{game_mode_title: 0},
	{LevelText: 0},
	{level: 0},
	{locked: 0},
	{Pin: 0},
	{LevelTileBG: 0},
	{LevelsBack: 0},
	{LevelsTopBG: 0},
	{LevelsTitle: 0},
	{PlayBtn: 0},
	{favBtn: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{logo_: 0},
	{LevelCompleteContentBG: 0},
	{CompleteLevelTxt: 0},
	{CompleteTxt: 0},
	{NextLevelBtn: 0},
	{LevelCompleteBG: 0},
	{LevelCompleteMenuBtn: 0},
	{LevelCompleteRestartBtn: 0},
	{LevelCompleteSoundBtn: 0},
	{GameRestartBtn: 0},
	{Liquid: 0},
	{GameLevelTxt: 0},
	{holder: 0},
	{menu_btn: 0},
	{RulesImg: 0},
	{LiquidBody: 0},
	{LiquidBottom: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Name: 0},
	{SimpleEvent: 0},
	{SoundBtn: 0},
	{Background: 0},
	{Audio: 0},
	{Message: 0},
	{SoundEffect: 0},
	{Browser: 0},
	{BackgroundBlur: 0},
	{GameSpriteInstance: 0},
	{LiquidLine: 0},
	{WinParticle: 0},
	{WinParticles: 0},
	{PlaygamaBridge: 0},
	{temp: 0},
	{ExpectWidth: 0},
	{GameState: 0},
	{admobInterstialId: 0},
	{SelectedLevelGroup: 0},
	{SelectedLevel: 0},
	{LastMousePosition: 0},
	{CurrentMousePosition: 0},
	{MaxLevelPanelY: 0},
	{Sound: 0},
	{FirstTime: 0},
	{StoreUrl: 0}
];

self.InstanceType = {
	EasyBtn: class extends self.ISpriteInstance {},
	MediumBtn: class extends self.ISpriteInstance {},
	HardBtn: class extends self.ISpriteInstance {},
	GameModeBack: class extends self.ISpriteInstance {},
	game_mode_title: class extends self.ISpriteInstance {},
	LevelText: class extends self.ITextInstance {},
	LevelTileBG: class extends self.ISpriteInstance {},
	LevelsBack: class extends self.ISpriteInstance {},
	LevelsTopBG: class extends self.ISpriteInstance {},
	LevelsTitle: class extends self.ITextInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	favBtn: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	logo_: class extends self.ISpriteInstance {},
	LevelCompleteContentBG: class extends self.ISpriteInstance {},
	CompleteLevelTxt: class extends self.ITextInstance {},
	CompleteTxt: class extends self.ITextInstance {},
	NextLevelBtn: class extends self.ISpriteInstance {},
	LevelCompleteBG: class extends self.ISpriteInstance {},
	LevelCompleteMenuBtn: class extends self.ISpriteInstance {},
	LevelCompleteRestartBtn: class extends self.ISpriteInstance {},
	LevelCompleteSoundBtn: class extends self.ISpriteInstance {},
	GameRestartBtn: class extends self.ISpriteInstance {},
	Liquid: class extends self.ISpriteInstance {},
	GameLevelTxt: class extends self.ITextInstance {},
	holder: class extends self.ISpriteInstance {},
	menu_btn: class extends self.ISpriteInstance {},
	RulesImg: class extends self.ISpriteInstance {},
	LiquidBody: class extends self.ISpriteInstance {},
	LiquidBottom: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	SimpleEvent: class extends self.ISpriteInstance {},
	SoundBtn: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	SoundEffect: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	BackgroundBlur: class extends self.ISpriteInstance {},
	GameSpriteInstance: class extends self.ISpriteInstance {},
	LiquidLine: class extends self.ISpriteInstance {},
	WinParticle: class extends self.ISpriteInstance {},
	WinParticles: class extends self.ISpriteInstance {},
	PlaygamaBridge: class extends C3.Plugins.PlaygamaBridge.Instance {}
}